exp_name: None


dist: 'mobiusflow'
# circularsplineflow, mobiusflow, mobiusflow_3D, mobiusflow_theta, fisher, relie_non_compact, relie_compact
condition: 1
feature_dim: 2048

layers: 24
segments: 64
rot: '16Trans'

data_dir: 'data'
dataset: 'modelnet'
# 'modelnet', 'pascal3d'

category: 'all'
category_num: 10
embedding: 1
embedding_dim: 32

#cont: True
#cont_ckpt: 'mobiusflow_3D_sofa_modelnet_b32_lr1.0e-04/Sep12_221117/ckpt_iteration190000'

network: 'resnet101'
pretrain_fisher: 1

lr: 1e-4
batch_size: 128
lr_decay: "30,40"
gamma: 0.1
num_workers: 4
max_iteration: 500000
log_frequency: 20
val_frequency: 2500
save_frequency: 5000
number_queries: 500
gpu: 0
eval_train: 'acc'

eval: 'log' # can also be 'sample', or 'pdf'
# if use 'sample' or 'pdf', please specify eval_category and vis_idx
# you can also change size of number_queries to obtain better visualization
#vis_idx: 10
eval_category: 'toilet'