exp_name: None
dist: 'mobiusflow'

condition: 0

layers: 24
segments: 64
rot: '16Trans'

data_dir: 'data'
dataset: 'raw'

category: 'peak'
# can be 'fisher24', 'line', 'cone', 'peak'
category_num: 1
embedding: 0


lr: 1e-4
batch_size: 1024
num_workers: 4
max_iteration: 50000
log_frequency: 20
val_frequency: 250
save_frequency: 5000
number_queries: 5000
gpu: 0
eval_train: 'nll'
eval: 'nll' # can be nll, sample, pdf
# if one use pdf to plot picture, it requires large number_queries, at least 500_000
