name: Python Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Cache data directory
      uses: actions/cache@v2
      with:
        path: ./data
        key: data-${{ github.run_id }}
        restore-keys: |
          data-

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        load: true
        tags: my-image:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    - name: List images
      run: docker images

    - name: Run tests
      run: |
        docker run --ipc=host -v ${{ github.workspace }}:/workspace my-image:latest /bin/bash -c "\
          pip install -r requirements.txt torch-tb-profiler pytest && \
          /bin/bash download_modelnet10-SO3-dataset.sh && \
          python -m unittest discover"